### ISSUE TITLE
I2C STM32 support

### ISSUE THREAD

**Issue by eden-desta** [lileibin/MS5803#1]
Hi! This library looks really great! I was wondering if there was an I2C equivalent you would know off or what it would look like to transition this to I2C?

**Comment by lileibin** [comment]
I‘m sorry about that i get no ms5803 now. I will add I2C driver later.

**Comment by eden-desta** [comment]
Sweet! Thank you I appreciate it! Let me know how I can help

**Comment by eden-desta** [comment]
@lileibin Just a couple of questions! Thank you in advance!
I began converting the calls over myself (the only difference is the board that I am using nucleo_h743zi2)

I am using PB6 - SDA and PB7 as SCL
I seem to have a problem with the write command:
for your reference the CSB_HIGH is 0x76 from the data sheet i found. 
However, in this call when I call HAL_I2C_Master_Transmit it always fails with a HAL_ERROR. It seems to timeout. 

```
static int WriteCmd(I2C_HandleTypeDef * hi2c, uint8_t CMD) {
	memset(aTxBuffer,0,sizeof(aTxBuffer));
	aTxBuffer[0] = CMD;

	ClrCS();

	if(HAL_I2C_Master_Transmit(hi2c, (uint16_t) CSB_HIGH, (uint8_t*)aTxBuffer, 1, 100)) {
		SetCS();
		return 1;
	}
	else
	{
		SetCS();
		return 0;
	}
}

#define SetCS()							HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_SET)
```

I tried scoping out the output but I actually see no attempt in the system trying to transmit.

This failure is occuring in the ResetDevice Function that I call as part of the initialisation:
```
static void ResetDevice(I2C_HandleTypeDef * hi2c) {
	WriteCmd(hi2c, RESET);
	HAL_Delay(3);
}

void MS5803Init(I2C_HandleTypeDef * hi2c) {
	ResetDevice(hi2c);
	GetPromData(hi2c);
}
```

**Comment by eden-desta** [comment]
Actually seems as though it was due to a pull up resistor! Thank you!
